application: gsis-wsnp
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /
  static_files: templates/home.html
  upload: templates/home\.html
  
- url: /.*
  script: main.py

libraries:
- name: webapp2
  version: "2.5.2"
